$servip = 172.16.16.1/24
$subnet = 172.16.16.0/24
$endpoint = example.org:30000
$keeptime = 25
$wgport = 30000
$httport = 0.0.0.0:30001
$servpriv = uH6JidEPgxu+ycakKTg5r4jYKL1GCPnp7zLBGJ/TsWg=
$servpub = 65HBdqHth09LpPc6U0xhER60zRWY0Ct5BQVwuz1hmUE=